---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
spec:
  serviceName: redis-sentinel-service
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      containers:
        - name: redis-sentinel
          image: nickadam/redis-sentinel-statefulset:1
          env:
          - name: REDIS_POD_NAME
            value: "redis"
          - name: REDIS_SERVICE_NAME
            value: "redis-service"
          - name: REDIS_SENTINEL_POD_NAME
            value: "redis-sentinel"
          - name: REDIS_SENTINEL_SERVICE_NAME
            value: "redis-sentinel-service"
          - name: PASSWORD
            value: "badpassword"
          - name: INSTANCE_NAME
            value: "mycluster"
          command:
            - 'tini'
            - 'docker-entrypoint.sh'
            - 'redis-sentinel'
          ports:
            - containerPort: 26379
              name: sentinel
