---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pointman
  labels:
    app: pointman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pointman
  template:
    metadata:
      labels:
        app: pointman
    spec:
      containers:
      - name: pointman
        image: ubuntu
