---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis-service
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: "redis-hostpath"
          hostPath:
            path: "/srv/redis-hostpath"
      containers:
        - name: redis
          image: alpine
          command:
            - 'sleep'
            - '7000d'
          env:
          - name: GREETING
            value: "Warm greetings to"
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-hostpath
              mountPath: /data
