---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  clusterIP: None
  ports:
  - name: redis
    port: 6379
  - name: other
    port: 6380
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
spec:
  serviceName: myapp-service
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: diag:1
          command:
            - 'tini'
            - 'sleep'
            - '7000d'
          ports:
            - containerPort: 6379
        - name: myapp2
          image: diag:1
          command:
            - 'tini'
            - 'sleep'
            - '7000d'
          ports:
            - containerPort: 6380
