# rs.initiate( {
#    _id : "MainRepSet",
#    members: [
#       { _id: 0, host: "mongod-0.mongodb-service:27017" },
#       { _id: 1, host: "mongod-1.mongodb-service:27017" },
#       { _id: 2, host: "mongod-2.mongodb-service:27017" }
#    ]
# })

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongod
spec:
  serviceName: mongodb-service
  replicas: 3
  selector:
    matchLabels:
      role: mongo
  template:
    metadata:
      labels:
        role: mongo
        replicaset: MainRepSet
    spec:
      #volumes:
      #  - name: "mongodb-hostpath"
      #    hostPath:
      #      path: "/srv/mongodb-hostpath"
      containers:
        - name: mongod-container
          image: mongo
          command:
            - "tini"
            - "docker-entrypoint.sh"
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "MainRepSet"
          ports:
            - containerPort: 27017
          #volumeMounts:
          #  - name: mongodb-hostpath
          #    mountPath: /data/db
