# rs.initiate( {
#    _id : "MainRepSet",
#    members: [
#       { _id: 0, host: "mongo-0.mongodb-service:27017" },
#       { _id: 1, host: "mongo-1.mongodb-service:27017" },
#       { _id: 2, host: "mongo-2.mongodb-service:27017" }
#    ]
# })

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Pod
metadata:
  name: mongo-0
  labels:
    app: mongo
spec:
  terminationGracePeriodSeconds: 10
  volumes:
    - name: "mongodb-hostpath"
      hostPath:
        path: "/srv/mongo-0-hostpath"
  hostname: mongo-0
  subdomain: mongodb-service
  containers:
    - name: mongo
      image: mongo
      command:
        - "mongod"
        - "--bind_ip"
        - "0.0.0.0"
        - "--replSet"
        - "MainRepSet"
      ports:
        - containerPort: 27017
          name: mongo
      volumeMounts:
        - name: mongodb-hostpath
          mountPath: /data/db
---
apiVersion: v1
kind: Pod
metadata:
  name: mongo-1
  labels:
    app: mongo
spec:
  terminationGracePeriodSeconds: 10
  volumes:
    - name: "mongodb-hostpath"
      hostPath:
        path: "/srv/mongo-1-hostpath"
  hostname: mongo-1
  subdomain: mongodb-service
  containers:
    - name: mongo
      image: mongo
      command:
        - "mongod"
        - "--bind_ip"
        - "0.0.0.0"
        - "--replSet"
        - "MainRepSet"
      ports:
        - containerPort: 27017
          name: mongo
      volumeMounts:
        - name: mongodb-hostpath
          mountPath: /data/db
---
apiVersion: v1
kind: Pod
metadata:
  name: mongo-2
  labels:
    app: mongo
spec:
  terminationGracePeriodSeconds: 10
  volumes:
    - name: "mongodb-hostpath"
      hostPath:
        path: "/srv/mongo-2-hostpath"
  hostname: mongo-2
  subdomain: mongodb-service
  containers:
    - name: mongo
      image: mongo
      command:
        - "mongod"
        - "--bind_ip"
        - "0.0.0.0"
        - "--replSet"
        - "MainRepSet"
      ports:
        - containerPort: 27017
          name: mongo
      volumeMounts:
        - name: mongodb-hostpath
          mountPath: /data/db
